export type ConceptCategory = "Structure" | "Price Action" | "Zones" | "Risk" | "Sessions" | "Mindset";

export type ConceptFlashcard = {
  id: string;
  concept: string;
  kitchenName: string;
  category: ConceptCategory;
  front: string;
  back: string;
  example: string;
  chefTip: string;
  character: string;
  characterEmoji: string;
  xpValue: number;
  color: string;
};

export const CONCEPT_VAULT: ConceptFlashcard[] = [
  {
    id: "bias",
    concept: "Bias",
    kitchenName: "Kitchen Direction",
    category: "Structure",
    front: "What is Bias and why does the kitchen need direction?",
    back: "Bias is the overall directional lean of the market — Bullish (price expected to rise) or Bearish (price expected to fall). In TCU, Bias is the Kitchen Direction: every meal, every setup, every decision must align with it. Read Bias on higher timeframes (daily, 4H) before zooming into entries.",
    example: "Daily chart shows a series of higher highs and higher lows. Bias is Bullish. Every setup on the 1H and 15m should favor long entries — cooking upward.",
    chefTip: "Grandma Market says: never trade against the kitchen direction without a very strong structural reason. The restaurant wins when the whole team moves together.",
    character: "Grandma Market",
    characterEmoji: "👵",
    xpValue: 10,
    color: "violet",
  },
  {
    id: "liquidity",
    concept: "Liquidity",
    kitchenName: "The Gold Flow",
    category: "Price Action",
    front: "What is Liquidity and where does price go to hunt it?",
    back: "Liquidity is the pool of resting stop orders sitting above swing highs (buy-side) or below swing lows (sell-side). Institutional price movement hunts these pools before making the real directional move. Louie calls it the Gold Flow — where price actually feeds before it delivers.",
    example: "Price sweeps yesterday's high, triggering retail buy-stops, then sharply reverses downward. That sweep was the liquidity grab. The real move happened after.",
    chefTip: "Louie says: mark your swing highs and lows every session. Liquidity lives there. Wait for the sweep before committing to direction.",
    character: "Louie",
    characterEmoji: "💧",
    xpValue: 10,
    color: "amber",
  },
  {
    id: "aoi",
    concept: "AOI",
    kitchenName: "The Prep Zone",
    category: "Zones",
    front: "What is an Area of Interest (AOI / Prep Zone)?",
    back: "An AOI is a price zone where you expect a meaningful market reaction — a supply or demand area, a previous consolidation level, an FVG, or a key structural point. In TCU, it is the Prep Zone: the spot where price is expected to pause and set up before the next move.",
    example: "Price drops from a high into a previous demand zone on the 4H. That demand area is the AOI — where bulls might step back in and price could reverse.",
    chefTip: "Chef Maurice says: not every zone is an AOI. Only mark zones aligned with your bias that have structural backing. Quality over quantity.",
    character: "Chef Maurice",
    characterEmoji: "👨‍🍳",
    xpValue: 10,
    color: "violet",
  },
  {
    id: "fvg",
    concept: "FVG",
    kitchenName: "Gap in the Pantry",
    category: "Price Action",
    front: "What is a Fair Value Gap (FVG)?",
    back: "An FVG is a 3-candle price imbalance where the market moved so quickly that a 'gap' was left between candle 1's high and candle 3's low (bullish FVG), or candle 1's low and candle 3's high (bearish FVG). Price frequently returns to fill this Gap in the Pantry before continuing.",
    example: "Three consecutive bullish candles — the gap between the body of candle 1's high wick and candle 3's low wick is the FVG. Price may pull back into this zone before continuing up.",
    chefTip: "Wickie says: FVGs in the direction of your Bias are the entries. Wait for price to return to the gap, then look for candle confirmation before entering.",
    character: "Wickie",
    characterEmoji: "🕯️",
    xpValue: 15,
    color: "blue",
  },
  {
    id: "ifvg",
    concept: "IFVG",
    kitchenName: "The Inner Gap",
    category: "Price Action",
    front: "What is an Inner FVG (IFVG)?",
    back: "An IFVG is a smaller imbalance nested inside a larger FVG. It is a refined, more precise entry zone — found within the bigger gap when you zoom into a lower timeframe. Higher precision = better risk-to-reward.",
    example: "Price retraces into a bullish 4H FVG. Switching to 15m reveals a smaller 3-candle gap within it. That smaller gap is the IFVG — the precision entry.",
    chefTip: "Wickie says: use IFVGs when you want a tighter stop and a better entry. They reward patience and precision over speed.",
    character: "Wickie",
    characterEmoji: "🕯️",
    xpValue: 20,
    color: "blue",
  },
  {
    id: "bos",
    concept: "BOS",
    kitchenName: "The Kitchen Turn",
    category: "Structure",
    front: "What is a Break of Structure (BOS)?",
    back: "A BOS occurs when price breaks a significant swing high (in a bullish move) or swing low (in a bearish move), confirming that the current directional momentum is continuing. A BOS validates your bias and signals the kitchen is turning as expected.",
    example: "In an uptrend, price pulls back, then breaks above the previous swing high with a strong bullish candle. That is the BOS — kitchen direction confirmed upward.",
    chefTip: "Chef Maurice says: a BOS following a liquidity sweep is confirmation of the real move. Wait for it before entering — don't guess.",
    character: "Chef Maurice",
    characterEmoji: "👨‍🍳",
    xpValue: 15,
    color: "emerald",
  },
  {
    id: "choch",
    concept: "CHOCH",
    kitchenName: "The Direction Switch",
    category: "Structure",
    front: "What is a Change of Character (CHOCH)?",
    back: "A CHOCH signals the earliest sign of a potential reversal — the first time price breaks structure against the current trend direction. It does not confirm the reversal alone, but it warns that the Kitchen Direction may be switching.",
    example: "After a prolonged downtrend, price breaks above a recent swing high for the first time. That is a CHOCH. Direction may be switching from Bearish to Bullish.",
    chefTip: "Grandma Market says: a CHOCH alone is not an entry signal. Wait for the follow-through BOS on a lower timeframe to confirm the new direction before committing.",
    character: "Grandma Market",
    characterEmoji: "👵",
    xpValue: 20,
    color: "indigo",
  },
  {
    id: "delivery",
    concept: "Delivery",
    kitchenName: "Price on the Move",
    category: "Price Action",
    front: "What is Delivery in TCU and how do you read it?",
    back: "Delivery describes how price moves between liquidity zones and AOIs — the actual mechanism of directional price action. Understanding delivery helps you anticipate how far and how fast price will travel after a sweep or BOS. Clean delivery = strong bodies, minimal wicks, limited retracement.",
    example: "After sweeping sell-side liquidity, price delivers bullishly through a FVG toward the AOI in four clean, large-body candles. Louie calls that a clean delivery.",
    chefTip: "Louie says: watch the character of candles during delivery. Indecisive wicks or choppy back-and-forth means weak delivery — wait for clarity before entering.",
    character: "Louie",
    characterEmoji: "💧",
    xpValue: 15,
    color: "cyan",
  },
  {
    id: "confirmation",
    concept: "Confirmation",
    kitchenName: "Candle Proof",
    category: "Price Action",
    front: "What is Confirmation (Candle Proof) in TCU?",
    back: "Confirmation is the candlestick signal that proves the market is ready to move in your anticipated direction. It is the Candle Proof you need before entry — an engulfing candle, a rejection wick, a displacement candle, or a close above/below a key level at your AOI.",
    example: "Price reaches the AOI. A strong bullish engulfing candle forms with a long lower wick rejecting the low. The close above the previous candle's open is the Candle Proof.",
    chefTip: "Wickie says: no confirmation means no entry. This step separates disciplined students from emotional traders. Wait for the market to agree with your plan.",
    character: "Wickie",
    characterEmoji: "🕯️",
    xpValue: 10,
    color: "blue",
  },
  {
    id: "targets",
    concept: "Targets",
    kitchenName: "Tables Served",
    category: "Risk",
    front: "What are Targets and how do you define Tables Served?",
    back: "Targets are your planned profit-taking levels — the price zones where you intend to close all or part of your position. In TCU, these are Tables Served: the meals you're delivering to your guests. Know where you are serving before you start cooking.",
    example: "Previous equal highs at 2360, a bearish FVG at 2355, and a daily liquidity pool at 2370. Mark all three. Those are your Tables Served.",
    chefTip: "Profit Plate says: if you don't know where you're delivering, you're just guessing. Mark your targets before entry — not after.",
    character: "Profit Plate",
    characterEmoji: "🍽️",
    xpValue: 10,
    color: "emerald",
  },
  {
    id: "management",
    concept: "Management",
    kitchenName: "Protect the Plate",
    category: "Risk",
    front: "What is Trade Management (Protect the Plate)?",
    back: "Management is everything you do after entry — moving your stop to break-even, scaling out at Target 1, letting a runner toward Target 2, or closing early when the setup invalidates. It is how you protect what you have already cooked.",
    example: "Entry at 2341. Price hits Target 1 at 2355. Move stop to break-even at 2341. Let the remaining position run toward Target 2 at 2368. Journal the thinking.",
    chefTip: "Burn Alarm says: the entry is just the beginning. Management is where accounts grow or collapse. Practice a management plan for every ticket in your journal.",
    character: "Burn Alarm",
    characterEmoji: "🚨",
    xpValue: 15,
    color: "rose",
  },
  {
    id: "ny-session",
    concept: "NY Breakfast Rush",
    kitchenName: "Morning Service",
    category: "Sessions",
    front: "What is the NY Breakfast Rush in TCU?",
    back: "The New York Session open (8AM–10AM EST) is the highest-volume, most volatile trading window of the day — especially for Gold (XAUUSD) and Forex majors. TCU names this the NY Breakfast Rush: the busiest service shift where the real money moves.",
    example: "Gold consolidates overnight. At 7:45 AM EST, price sweeps buy-side liquidity above the Asian range. By 8:10 AM, a clean bearish delivery begins. Classic Breakfast Rush sweep-and-deliver.",
    chefTip: "Chef Maurice says: the first 30–60 minutes of NY often sets the tone for the entire day. Watch the 8AM candle direction before committing to a side.",
    character: "Chef Maurice",
    characterEmoji: "👨‍🍳",
    xpValue: 10,
    color: "amber",
  },
  {
    id: "london-session",
    concept: "London Session",
    kitchenName: "The Prep Shift",
    category: "Sessions",
    front: "What is the London Session (Prep Shift) in TCU?",
    back: "London opens at 3AM EST and runs through noon. This is the Prep Shift — where many institutional directional moves begin. Gold and Forex pairs see expanded liquidity and sharp structural moves during this window before NY opens.",
    example: "Gold sweeps the Asian session low at 3:30 AM EST, forms a bullish FVG, then consolidates. When NY opens at 8 AM, price continues the bullish delivery started in London.",
    chefTip: "Grandma Market says: London often creates the structural setup that NY confirms. Study the 4H chart before each London session open.",
    character: "Grandma Market",
    characterEmoji: "👵",
    xpValue: 10,
    color: "indigo",
  },
  {
    id: "overtrading",
    concept: "Overtrading",
    kitchenName: "Kitchen Chaos",
    category: "Mindset",
    front: "What is Overtrading and why does Melissa Mayhem love it?",
    back: "Overtrading is taking more trades than your plan allows — driven by FOMO, boredom, revenge after a loss, or the illusion of opportunity. Melissa Mayhem thrives on Kitchen Chaos. Overtrading destroys discipline, compounds losses, and erases profitable sessions.",
    example: "You take 2 planned trades and lose both. Out of frustration you take 4 more unplanned trades, none aligned with the roadmap. That is Kitchen Chaos — Melissa has taken over.",
    chefTip: "Burn Alarm says: set a daily session limit of 2–3 setups maximum. Once the limit is reached, close the charts. A missed trade never hurts you. A revenge trade always does.",
    character: "Melissa Mayhem",
    characterEmoji: "😤",
    xpValue: 15,
    color: "orange",
  },
  {
    id: "patience",
    concept: "Patience Rule",
    kitchenName: "Grandma's Rule",
    category: "Mindset",
    front: "What is Grandma Market's Patience Rule?",
    back: "Grandma Market's Rule: If the setup does not satisfy all 8 roadmap steps — Bias, Liquidity, AOI, Delivery, Confirmation, Entry, Targets, Management — then close the chart and walk away. The market will serve another plate tomorrow. Forced trades are burnt food.",
    example: "Bias is unclear. No liquidity sweep visible. The AOI is ambiguous. Yet you feel the urge to trade. Grandma sends that plate back to the kitchen.",
    chefTip: "Grandma Market says: patience is not passivity. Every day you do not overtrade, you protect your capital and your confidence. Both compound over time.",
    character: "Grandma Market",
    characterEmoji: "👵",
    xpValue: 20,
    color: "indigo",
  },
  {
    id: "burn-point",
    concept: "Burn Point",
    kitchenName: "The Stop Loss",
    category: "Risk",
    front: "What is the Burn Point and why does Burn Alarm always check for it?",
    back: "The Burn Point is your stop loss — the specific price level where the trade is structurally invalidated and you accept the planned loss. It is not negotiable. Burn Alarm rings loudly for every ticket that is missing one.",
    example: "You buy Gold at 2341. The AOI demand zone low is 2334. Your Burn Point is placed at 2332 — below the structure and the recent swing low.",
    chefTip: "Burn Alarm says: no Burn Point defined = no trade taken. A missing stop is not confidence — it is recklessness. Define it first, always.",
    character: "Burn Alarm",
    characterEmoji: "🚨",
    xpValue: 10,
    color: "rose",
  },
];

export const CONCEPT_CATEGORIES: ConceptCategory[] = [
  "Structure",
  "Price Action",
  "Zones",
  "Risk",
  "Sessions",
  "Mindset",
];

export const CATEGORY_COLORS: Record<ConceptCategory, string> = {
  Structure:    "bg-emerald-500/15 border-emerald-500/40 text-emerald-300",
  "Price Action": "bg-blue-500/15 border-blue-500/40 text-blue-300",
  Zones:        "bg-violet-500/15 border-violet-500/40 text-violet-300",
  Risk:         "bg-rose-500/15 border-rose-500/40 text-rose-300",
  Sessions:     "bg-amber-500/15 border-amber-500/40 text-amber-300",
  Mindset:      "bg-indigo-500/15 border-indigo-500/40 text-indigo-300",
};
