import type { MarketSymbol, MarketCategory, Watchlist } from "./types";

// Full TradingView symbol identifiers — exchange:pair format
export const TV_SYMBOL_MAP: Record<string, string> = {
  XAUUSD:  "OANDA:XAUUSD",
  GOLD:    "TVC:GOLD",
  EURUSD:  "OANDA:EURUSD",
  GBPUSD:  "OANDA:GBPUSD",
  USDJPY:  "OANDA:USDJPY",
  AUDUSD:  "OANDA:AUDUSD",
  USDCAD:  "OANDA:USDCAD",
  NAS100:  "CAPITALCOM:US100",
  US30:    "CAPITALCOM:US30",
  SPX:     "TVC:SPX",
  SPY:     "AMEX:SPY",
  QQQ:     "NASDAQ:QQQ",
  AAPL:    "NASDAQ:AAPL",
  TSLA:    "NASDAQ:TSLA",
  NVDA:    "NASDAQ:NVDA",
  MSFT:    "NASDAQ:MSFT",
  AMZN:    "NASDAQ:AMZN",
  META:    "NASDAQ:META",
  BTCUSD:  "BITSTAMP:BTCUSD",
  ETHUSD:  "BITSTAMP:ETHUSD",
};

export function resolveTVSymbol(ticker: string): string {
  if (ticker === "XAUUSD") {
    return TV_SYMBOL_MAP.XAUUSD || TV_SYMBOL_MAP.GOLD;
  }

  return TV_SYMBOL_MAP[ticker] ?? TV_SYMBOL_MAP.GOLD;
}

export const MARKET_SYMBOLS: MarketSymbol[] = [
  {
    ticker: "XAUUSD",
    name: "Gold / US Dollar",
    category: "Gold",
    tvSymbol: "OANDA:XAUUSD",
    tvFallbackSymbol: "TVC:GOLD",
    basePrice: "2,341.80",
    change: "+8.40",
    changePercent: "+0.36%",
    bias: "Bullish",
    session: "NY Session",
  },
  {
    ticker: "EURUSD",
    name: "Euro / US Dollar",
    category: "Forex",
    tvSymbol: "FX:EURUSD",
    basePrice: "1.0842",
    change: "-0.0015",
    changePercent: "-0.14%",
    bias: "Bearish",
    session: "London",
  },
  {
    ticker: "GBPUSD",
    name: "British Pound / US Dollar",
    category: "Forex",
    tvSymbol: "FX:GBPUSD",
    basePrice: "1.2691",
    change: "+0.0022",
    changePercent: "+0.17%",
    bias: "Bullish",
    session: "London",
  },
  {
    ticker: "USDJPY",
    name: "US Dollar / Japanese Yen",
    category: "Forex",
    tvSymbol: "FX:USDJPY",
    basePrice: "157.42",
    change: "+0.32",
    changePercent: "+0.20%",
    bias: "Bullish",
    session: "Asia",
  },
  {
    ticker: "NAS100",
    name: "Nasdaq 100",
    category: "Indices",
    tvSymbol: "CAPITALCOM:US100",
    basePrice: "19,842.50",
    change: "+124.30",
    changePercent: "+0.63%",
    bias: "Bullish",
    session: "NY Session",
  },
  {
    ticker: "SPY",
    name: "S&P 500 ETF (SPDR)",
    category: "ETFs",
    tvSymbol: "AMEX:SPY",
    basePrice: "527.80",
    change: "+3.20",
    changePercent: "+0.61%",
    bias: "Bullish",
    session: "NY Session",
  },
  {
    ticker: "QQQ",
    name: "Nasdaq 100 ETF (Invesco)",
    category: "ETFs",
    tvSymbol: "NASDAQ:QQQ",
    basePrice: "448.24",
    change: "+5.10",
    changePercent: "+1.15%",
    bias: "Bullish",
    session: "NY Session",
  },
  {
    ticker: "AAPL",
    name: "Apple Inc.",
    category: "Stocks",
    tvSymbol: "NASDAQ:AAPL",
    basePrice: "189.84",
    change: "+1.42",
    changePercent: "+0.75%",
    bias: "Bullish",
    session: "NY Session",
  },
  {
    ticker: "TSLA",
    name: "Tesla Inc.",
    category: "Stocks",
    tvSymbol: "NASDAQ:TSLA",
    basePrice: "248.23",
    change: "-4.15",
    changePercent: "-1.64%",
    bias: "Bearish",
    session: "NY Session",
  },
  {
    ticker: "NVDA",
    name: "NVIDIA Corporation",
    category: "Stocks",
    tvSymbol: "NASDAQ:NVDA",
    basePrice: "874.15",
    change: "+22.40",
    changePercent: "+2.63%",
    bias: "Bullish",
    session: "NY Session",
  },
  {
    ticker: "MSFT",
    name: "Microsoft Corporation",
    category: "Stocks",
    tvSymbol: "NASDAQ:MSFT",
    basePrice: "414.20",
    change: "+1.80",
    changePercent: "+0.44%",
    bias: "Bullish",
    session: "NY Session",
  },
  {
    ticker: "AMZN",
    name: "Amazon.com Inc.",
    category: "Stocks",
    tvSymbol: "NASDAQ:AMZN",
    basePrice: "184.72",
    change: "+2.31",
    changePercent: "+1.27%",
    bias: "Bullish",
    session: "NY Session",
  },
  {
    ticker: "META",
    name: "Meta Platforms Inc.",
    category: "Stocks",
    tvSymbol: "NASDAQ:META",
    basePrice: "503.64",
    change: "+7.82",
    changePercent: "+1.58%",
    bias: "Bullish",
    session: "NY Session",
  },
  {
    ticker: "BTCUSD",
    name: "Bitcoin / US Dollar",
    category: "Crypto",
    tvSymbol: "BITSTAMP:BTCUSD",
    basePrice: "67,842.00",
    change: "+1,204.00",
    changePercent: "+1.81%",
    bias: "Bullish",
    session: "24/7",
  },
  {
    ticker: "ETHUSD",
    name: "Ethereum / US Dollar",
    category: "Crypto",
    tvSymbol: "BITSTAMP:ETHUSD",
    basePrice: "3,512.40",
    change: "+88.20",
    changePercent: "+2.58%",
    bias: "Bullish",
    session: "24/7",
  },
];

export const SYMBOL_CATEGORIES: MarketCategory[] = ["Gold", "Forex", "Stocks", "ETFs", "Crypto", "Indices"];

export const DEFAULT_SYMBOL = MARKET_SYMBOLS[0];

// Curated watchlists shown in the symbol search panel
export const WATCHLISTS: Watchlist[] = [
  {
    key:     "favorites",
    label:   "Favorites",
    emoji:   "⭐",
    symbols: [],
  },
  {
    key:     "gold",
    label:   "Gold Kitchen",
    emoji:   "🥇",
    symbols: ["XAUUSD", "GOLD"],
  },
  {
    key:     "forex",
    label:   "Forex Kitchen",
    emoji:   "💱",
    symbols: ["EURUSD", "GBPUSD", "USDJPY", "AUDUSD", "USDCAD"],
  },
  {
    key:     "stocks",
    label:   "Stocks Kitchen",
    emoji:   "📈",
    symbols: ["AAPL", "TSLA", "NVDA", "MSFT", "AMZN", "META", "SPY", "QQQ"],
  },
  {
    key:     "crypto",
    label:   "Crypto Kitchen",
    emoji:   "₿",
    symbols: ["BTCUSD", "ETHUSD"],
  },
  {
    key:     "indices",
    label:   "Indices Kitchen",
    emoji:   "🏛️",
    symbols: ["NAS100", "US30", "SPX"],
  },
];
